### ISSUE TITLE
Template "shopify" not found

### ISSUE THREAD

**Issue by AlexanderBMAS** [sanity-io/sanity-shopify-studio#3]
Error: Template "shopify" not found
    at e.default (~/.npm/_npx/97fe0ac6ea3bd86d/node_modules/@sanity/cli/bin/sanity-cli.js:4494:9253)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by robinpyon** [comment]
Hey @AlexanderBMAS,

It looks like you're trying to run `sanity init` on a non-tagged release of Sanity CLI.

Currently the `shopify` template is only available on the tagged `shopify` release – the following command should sort you out:
```
$ npx @sanity/cli@shopify init --template shopify
```

**Comment by AlexanderBMAS** [comment]
Thanks!

**Comment by robinpyon** [comment]
Just noticed that the README didn't point to the tagged release, sorry about that! That's been updated.
