### ISSUE TITLE
Upgrade Path

### ISSUE THREAD

**Issue by mikkopaderes-iona** [sanity-io/sanity-shopify-studio#32]
We've created a Sanity Studio using this Shopify template before. Upgrading to the latest Sanity has caused some config issues on our part specifically for the `colorProductOption`. It doesn't have the issue here as there was some changes made to fix it and we can copy-paste it in our Studio as well to fix it. But it got me thinking, how does someone upgrade our Studio to use the latest changes with Shopify template?

**Comment by thebiggianthead** [comment]
Hey @mikkopaderes-iona - the recent changes were made to support GraphQL and fix the studio warning you get in v3 as a result of a schema name clash. There is now [a script included in the repo](https://github.com/sanity-io/sanity-shopify-studio/blob/main/migrations/strictSchema.ts) to assist in the migration of data. There is some inline comments to act as a readme in this file. I'm assuming this is the changes you refer to?

Of course, it's always a good idea to backup your dataset and test these migrations (Studio and front-end) before applying them to a production dataset.

**Comment by mikkopaderes-iona** [comment]
@thebiggianthead thanks, I'll try this one out. I think I saw that before too but I thought of looking for something more generic. We haven't really touched anything default out of the box with this template so we wanted to have a go-to upgrade path incase there are some bugfixes committed here. Maybe forking is the better approach for us 🤔
