### ISSUE TITLE
Object names using periods appears to be incorrect according to Sanity documentation.

### ISSUE THREAD

**Issue by joeswann** [sanity-io/sanity-shopify-studio#4]
First thanks for a comprehensive template! Very excited to work with this and see where it goes.

I have run into an issue where part of https://github.com/ricokahler/sanity-codegen has a validator that is honoring the Sanity Documentation -- which states that object names can only have numbers, letters and underscores 
(https://www.sanity.io/docs/object-type#9a9a8b5c6404). 

This validator is rejecting this template as it uses periods for things like `article.editorial`and `seo.product`.

I am guessing that one of two things is true, either the Sanity Documentation (and therefore the sanity-codegen validation) is out of date and this template is correct, or this template should be using underscores for object names?

**Comment by joeswann** [comment]
There is a reproduction of this issue at https://github.com/1of1studio/repro-sanity-codegen - the only customisation is to add an alias for a sanity ui component to no-op in order to get sanity-codegen to run.

Note: Will require a projectId in sanity.json to run sanity of course

**Comment by joeswann** [comment]
Hi @robinpyon  and thank you for the quick response!

That's a great clarification, I have a couple of follow up thoughts to cover then:

- First - The documentation is a bit unclear on this because Sanity specifically states that documents are a kind of object, even going so far as to say `Apart from the above, documents are defined just like regular objects, so see the documentation of the object type for more info about how to define documents.`. This is a little loose though and it may not be intended to specifically include the field name validation, that idea would be bolstered if sanity uses 'sanity.fileAsset' already.

- Second, I think some of the objects actually do have a period in their field name, such as `seo.singleton`, `seo.standard` and `seo.product` - these do not appear to be documents? Could it be that they don't break Sanity due to their field name being different when actually applied (im not sure whether sanity validates the source object name or only the destination when referencing the object type in schema?).

Codegen may only be trying to generate types for externally defined schema, which might be why it wasn't already an issue with sanity.fileAsset... Not sure on that one!

**Comment by robinpyon** [comment]
No worries!

> First - The documentation is a bit unclear on this because Sanity specifically states that documents are a kind of object ... [t]his is a little loose though and it may not be intended to specifically include the field name validation ...

I should have been clearer by instead saying "periods in _object and document_ names are valid" instead. The docs are correct though – and the `fields` property on the document page does point to the fields section in the document page. 

That said, I agree with you that this is a little unclear. Given that `fields` are shared across both documents and objects, perhaps there's an argument for abstracting that out into a separate page.

> Second, I think some of the objects actually do have a period in their field name, such as seo.singleton, seo.standard and seo.product - these do not appear to be documents? 

That's correct, these are infact _objects_ which are referenced by other _documents_ (or even other _objects_).

> Im not sure whether Sanity validates the source object name or only the destination when referencing the object type in schema?).

Sanity will validate ALL object names at runtime (even if unreferenced) and will also throw errors when you try and reference an object that doesn't yet exist in your schema. 

I'm going to close this as I don't believe this issue likes with this specific studio setup, but please feel free to continue the conversation here!
