### ISSUE TITLE
Looks like the example sanity studio isn't working.

### ISSUE THREAD

**Issue by spacecamp** [sanity-io/sanity-shopify-studio#5]
The link in the about: [hydrogen-demo.sanity.studio](https://hydrogen-demo.sanity.studio/) isn't working. 
Not Found - Project with ID "wfr1r0dw" not found

Would love to see the backend sanity studio/ how the components work with the backend.

**Comment by robinpyon** [comment]
Hey @spacecamp! There shouldn't be a link to [hydrogen-demo.sanity.studio](https://hydrogen-demo.sanity.studio/) – are you able to point me to where you saw that link so I can remove it?

You can spin up your local copy of this studio by running either:
```
npx @sanity/cli@shopify init --template shopify
```
(which will give you the option to create a new Sanity project from scratch or link the studio to an existing project)

Alternatively, you can clone this repo and specify your own `projectId` in `sanity.json`

**Comment by spacecamp** [comment]
Hello @robinpyon! I see, I found the link on this github repo page: [https://github.com/sanity-io/sanity-shopify-studio](https://github.com/sanity-io/sanity-shopify-studio) Outlined the link in orange on the right:
![github_hydro](https://user-images.githubusercontent.com/5307354/177481359-3b55dd9a-415c-437d-8e1a-6ad186b4f395.png)

Awesome, I'll give the local copy of the template a try.
Does it populate the local sanity studio with the AKVA content, images, text, etc. too? I just wanted to see how you inputed content and images in sanity studio, to get an idea of how to upload, and get the same look and feel. 

Thanks much for the help! And amazing work, this template mixed in with sanity is next level, been able to learn a lot.

**Comment by robinpyon** [comment]
Ah of course – thank you, that's been updated!

> Does it populate the local sanity studio with the AKVA content, images, text, etc. too? 

Not yet unfortunately. We previously had this functionality exposed in [Sanity Connect](https://apps.shopify.com/sanity-connect), where users could pre-populate both an _empty_ Shopify store and their Sanity dataset with example content. However we've yet to find time to update this to account for collections too. Hopefully we can re-introduce this when we do another pass of the Shopify app in future.

> Thanks much for the help! And amazing work, this template mixed in with sanity is next level, been able to learn a lot.

Thank you for trying it out! Glad it's been helpful – please don't hesitate to raise an issue / start a discussion here, or reach out on [slack](https://slack.sanity.io/) if you have any questions.
