### ISSUE TITLE
isAvailable doesn't seem to return any value?

### ISSUE THREAD

**Issue by aeblin** [sanity-io/sanity-shopify-studio#7]
Using this studio as a starting spot for a project, and the isAvailable field doesn't seem to return anything currently. Is there an internal version of Shopify Connect that hasn't yet been publicly released that supports the field? As of right now, nothing is returned when I make a request for the field on the Shopify Product or Product Variant level via GROQ.

**Comment by aeblin** [comment]
@robinpyon And I sorted through this, though if you've found your way here through a search, you may need to reach out to the Sanity team to ask them to push through a flag to update your installation of Sanity Connect. Unfortunately just uninstalling/reinstalling the app (which has its own set of issues, be sure to clear your cache and cookies or just use an incognito tab when reinstalling) didn't seem to resolve the issue.

**Comment by robinpyon** [comment]
Thanks @aeblin!
