### ISSUE TITLE
Cannot get storeId

### ISSUE THREAD

**Issue by rodsotdia** [sanity-io/sanity-shopify-studio#9]
The function `getShopifyStoreId()` located at the file `utils/getShopifyStoreId.ts` returns nothing, which creates issues when trying to show the URLs to edit products/collections in Shopify (document actions).

I was checking the object fetched and there is no `sanity.shopify.sync` document type. 

Is there another way to get the store ID from the sanity client?

**Comment by robinpyon** [comment]
Thanks for flagging this, @rodsotdia. 

`getShopifyStoreId` is no longer relevant, as is the `sanity.shopify.sync` document it references – apologies for the confusion here.

The latest version of the studio addresses this. You will need to manually specify your `SHOPIFY_STORE_ID` in `constants.js`, but doing so will re-enable those document actions and other helper links.

**Comment by rodsotdia** [comment]
Nice, thanks for the quick response @robinpyon
